SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES, DEPARTMENTS;

SELECT  FIRST_NAME AS PRIMEIRO_NOME,
        E.DEPARTMENT_ID COD_DEPARTAMENTO,
        D.DEPARTMENT_ID,
        D.DEPARTMENT_NAME
FROM    EMPLOYEES E, DEPARTMENTS D
WHERE   E.DEPARTMENT_ID =
                      D.DEPARTMENT_ID
        AND FIRST_NAME = 'Diana';


SELECT    E.FIRST_NAME, E.LAST_NAME,
          E.SALARY, J.MIN_SALARY,   J.MAX_SALARY,
          J.JOB_TITLE
FROM      EMPLOYEES E, JOBS J
WHERE     E.SALARY
          BETWEEN J.MIN_SALARY AND   J.MAX_SALARY
          AND FIRST_NAME = 'Randall';

SELECT * FROM JOBS;


SELECT * FROM EMPLOYEES;

SELECT   E.FIRST_NAME,
         D.DEPARTMENT_NAME
FROM     EMPLOYEES E,
         DEPARTMENTS D
WHERE    E.DEPARTMENT_ID =
                          D.DEPARTMENT_ID(+);



SELECT   WORKER.FIRST_NAME
         ||' TRABALHA PARA ' ||
         MANAGER.FIRST_NAME
FROM     EMPLOYEES WORKER,
         EMPLOYEES MANAGER
WHERE    WORKER.MANAGER_ID =
                       MANAGER.EMPLOYEE_ID;
                  
SELECT * FROM EMPLOYEES;


SELECT FIRST_NAME,
           DEPARTMENT_NAME
    FROM   EMPLOYEES
           CROSS JOIN DEPARTMENTS;

SELECT  FIRST_NAME,
        EMPLOYEES.DEPARTMENT_ID,
        DEPARTMENTS.DEPARTMENT_ID,
        DEPARTMENT_NAME
FROM    EMPLOYEES
        INNER JOIN DEPARTMENTS
          ON EMPLOYEES.DEPARTMENT_ID =
            DEPARTMENTS.DEPARTMENT_ID;

SELECT   EMPLOYEE_ID, FIRST_NAME,
         DEPARTMENT_NAME
FROM     EMPLOYEES
         INNER JOIN DEPARTMENTS
           ON EMPLOYEES.DEPARTMENT_ID =
             DEPARTMENTS.DEPARTMENT_ID
WHERE   FIRST_NAME = 'Diana';


SELECT   E.FIRST_NAME,
         J.JOB_TITLE,
         D.DEPARTMENT_NAME
FROM     EMPLOYEES E
         INNER JOIN JOBS J
           ON E.JOB_ID = J.JOB_ID
         INNER JOIN DEPARTMENTS D 
           ON E.DEPARTMENT_ID =   D.DEPARTMENT_ID;
           
           
SELECT   WORKER.FIRST_NAME
         ||' TRABALHA PARA ' ||
         MANAGER.FIRST_NAME
FROM     EMPLOYEES WORKER
           LEFT JOIN EMPLOYEES MANAGER
             ON WORKER.MANAGER_ID =
                MANAGER.EMPLOYEE_ID;

SELECT  EMPLOYEE_ID, manager_id
FROM    EMPLOYEES WORKER
WHERE ROWNUM < 10;

SELECT EMPLOYEE_ID, manager_id
FROM  EMPLOYEES MANAGER
WHERE ROWNUM < 10;



SELECT   E.FIRST_NAME,
         D.DEPARTMENT_NAME
FROM     EMPLOYEES E FULL JOIN DEPARTMENTS D
             ON E.DEPARTMENT_ID =
                           D.DEPARTMENT_ID;
                           


