--1
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM   EMPLOYEES
WHERE  SALARY BETWEEN 0 AND 2000
       OR SALARY >= 5000;
       
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM   EMPLOYEES
WHERE  (SALARY >= 0 AND SALARY<= 2000) OR SALARY >= 5000;

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY 
FROM   EMPLOYEES
WHERE  SALARY NOT BETWEEN 2001 AND 4999;

--2
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, L.LOCATION_ID
FROM   DEPARTMENTS D
       INNER JOIN LOCATIONS L
         ON D.LOCATION_ID = L.LOCATION_ID
WHERE  L.LOCATION_ID BETWEEN 1500 AND 2000;


SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM   DEPARTMENTS D
WHERE  LOCATION_ID BETWEEN 1500 AND 2000;

--3
SELECT D.DEPARTMENT_NAME, E.FIRST_NAME
FROM   DEPARTMENTS D
       INNER JOIN EMPLOYEES E
         ON D.MANAGER_ID = E.EMPLOYEE_ID
       INNER JOIN LOCATIONS L
         ON L.LOCATION_ID = D.LOCATION_ID
WHERE L.CITY = 'Sao Paulo';

select * from locations WHERE CITY = 'Sao Paulo';
SELECT * FROM DEPARTMENTS WHERE LOCATION_ID = 2800;




